### ISSUE TITLE
Failed to load kext net.lundman.zfs

### ISSUE THREAD

**Issue by aes512** [zfsrogue/osx-zfs-crypto#6]
Can't load kext net.lundman.zfs - link failed.
Failed to load executable for kext net.lundman.zfs.
Kext net.lundman.zfs failed to load (0xdc008016).
Failed to load kext net.lundman.zfs (error 0xdc008016).
kxld[net.lundman.zfs]: The following symbols were defined more than once:
kxld[net.lundman.zfs]: 	_tsd_get: 0xffffff7fa13938e0 - 0xffffff7fa12f99b0
kxld[net.lundman.zfs]: 	_tsd_set: 0xffffff7fa13938f0 - 0xffffff7fa12f9880
Can't load kext net.lundman.zfs - link failed.
Failed to load executable for kext net.lundman.zfs.
Kext net.lundman.zfs failed to load (0xdc008016).
Failed to load kext net.lundman.zfs (error 0xdc008016).

**Comment by zfsrogue** [comment]
fixed long time back
